spring.datasource.url=jdbc:mysql://localhost:3306/springbootdem
spring.datasource.username=root
spring.datasource.password=sql7wooJ5
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.mvc.hiddenmethod.filter.enabled=true
